name: Deploy to Droplet

on:
  push:
    branches:
      - master # Thay bằng main nếu bạn dùng nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            # Kiểm tra và clone repo nếu thư mục chưa tồn tại
            if [ ! -d "$HOME/CICDTest" ]; then
              git clone https://github.com/tantaivo2003/CICDTest.git $HOME/CICDTest
            fi

            cd $HOME/CICDTest

            git pull origin master

            # Ghi các biến môi trường từ GitHub Secrets
            printf "%s" "${{ secrets.BE_ENV }}" > be/.env
            printf "%s" "${{ secrets.FE_ENV }}" > todolist/.env

            docker compose down
            docker compose up --build -d
