name: Deploy to Droplet

on:
  push:
    branches:
      - master # Thay bằng main nếu bạn dùng nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/CICDTest   # Thư mục chứa project trên server
            echo "${{ secrets.BE_ENV }}" > be/.env
            echo "${{ secrets.FE_ENV }}" > todolist/.env
            git pull origin master
            docker compose down
            docker compose up --build -d
